export const ACHIEVEMENTS = Object.freeze([
  {
    icon: '✩',
    title: { fr: 'Tech Lead', en: 'Tech Lead' },
    desc: { fr: 'Pilotage d’équipe · transactions financières · 4 marques', en: 'Team leadership · financial transactions · 4 brands' },
    year: 'InVivo Digital Factory · 2024 →',
    tier: 'legendary',
  },
  {
    icon: '◈',
    title: { fr: 'Dev augmenté', en: 'AI-augmented dev' },
    desc: { fr: 'Agents, skills, second cerveau — chaque session capitalise sur la précédente', en: 'Agents, skills, second brain — every session compounds on the last' },
    year: 'compound engineering · 2025 →',
    tier: 'epic',
  },
  {
    icon: '⚖',
    title: { fr: 'Refonte transactionnelle', en: 'Transactional rewrite' },
    desc: { fr: 'Du panier à la commande — migration complète des flux', en: 'Cart to order — complete flow migration' },
    year: 'InVivo · 2023',
    tier: 'epic',
  },
  {
    icon: '⚙',
    title: { fr: 'Brique logistique', en: 'Logistics module' },
    desc: { fr: 'Architecture d’un module logistique partagé multi-enseignes', en: 'Shared logistics module architecture across brands' },
    year: 'InVivo · 2022',
    tier: 'standard',
  },
  {
    icon: '🎾',
    title: { fr: 'Roland-Garros', en: 'Roland-Garros' },
    desc: { fr: 'Billetterie du tournoi — rg.com', en: 'Tournament ticketing system — rg.com' },
    year: 'OCTO Technology · 2019',
    tier: 'standard',
  },
  {
    icon: '🇫🇷',
    title: { fr: 'numerique.gouv.fr', en: 'numerique.gouv.fr' },
    desc: { fr: 'Site officiel de la DINSIC — service public numérique', en: 'Official DINSIC website — French digital public service' },
    year: 'OCTO · DINSIC · 2019',
    tier: 'epic',
  },
  {
    icon: '🌱',
    title: { fr: 'Aladin.farm', en: 'Aladin.farm' },
    desc: { fr: 'Plateforme B2Ag pour le monde agricole — consultant puis interne', en: 'B2Ag platform for agriculture — consultant, then in-house' },
    year: 'InVivo Digital Factory · 2018 →',
    tier: 'standard',
  },
  {
    icon: '🚀',
    title: { fr: 'Premier drone', en: 'First drone' },
    desc: { fr: 'Chef de projet 2 ans — ECE Inov-Award', en: 'Project lead 2 years — ECE Inov-Award' },
    year: 'ECE · 2012 — 2014',
    tier: 'standard',
  },
  {
    icon: '⛰',
    title: { fr: 'Diplôme d’ingénieur', en: 'Engineering Degree' },
    desc: { fr: 'Systèmes d’information — ECE Paris', en: 'Information Systems — ECE Paris' },
    year: 'ECE · 2018',
    tier: 'standard',
  },
  {
    icon: '⚔',
    title: { fr: 'Chef scout', en: 'Scout leader' },
    desc: { fr: 'Encadrement · transmission · plein air', en: 'Leadership · passing on · outdoors' },
    year: 'Scouts Unitaires de France',
    tier: 'standard',
  },
]);
