export const POIS = Object.freeze([
  // ── CODE ──
  {
    id: 'jardiland', zone: 'code', top: 15, left: 12,
    name: { fr: 'Jardiland · Gammvert', en: 'Jardiland · Gammvert' },
    ctx: { fr: 'invivo digital factory · 2021—now', en: 'invivo digital factory · 2021—now' },
    desc: { fr: 'E-commerce multi-enseignes. Paiement, logistique, intégration SAP.', en: 'Multi-brand e-commerce. Payment, logistics, SAP integration.' },
    color: '#22d3ee', link: '', img: '',
    tip: { fr: 'Jardiland', en: 'Jardiland' },
  },
  {
    id: 'rg', zone: 'code', top: 14, left: 28,
    name: { fr: 'Roland-Garros', en: 'Roland-Garros' },
    ctx: { fr: 'octo · rg.com · 2019', en: 'octo · rg.com · 2019' },
    desc: { fr: 'Billetterie du tournoi de Roland-Garros.', en: 'Tournament ticketing system for Roland-Garros.' },
    color: '#22d3ee', link: '', img: '',
    tip: { fr: 'Roland-Garros', en: 'Roland-Garros' },
  },
  {
    id: 'idlecrusade', zone: 'code', top: 18, left: 41,
    name: { fr: 'Idle Crusade', en: 'Idle Crusade' },
    ctx: { fr: 'vite · svelte · 2026', en: 'vite · svelte · 2026' },
    desc: { fr: 'Idle game médiéval. Tu construis ton armée, elle se bat toute seule, tu pars en croisade pour repartir plus fort.', en: 'Medieval idle game. Build your army, it fights on its own, then crusade to reset and come back stronger.' },
    color: '#22d3ee', link: 'https://etienne-bernoux.github.io/Idle-Crusade/', img: '',
    tip: { fr: 'Idle Crusade', en: 'Idle Crusade' },
  },
  {
    id: 'carillon', zone: 'code', top: 33, left: 21,
    name: { fr: 'Carillon', en: 'Carillon' },
    ctx: { fr: 'typescript · vite · 2026', en: 'typescript · vite · 2026' },
    desc: { fr: 'Bac à sable musical : on dessine des barres, on lâche des billes, chaque rebond joue une note. La géométrie accorde l’instrument, et la scène entière tient dans son URL.', en: 'A musical sandbox: draw bars, drop marbles, every bounce plays a note. Geometry tunes the instrument, and the whole scene fits in its URL.' },
    color: '#22d3ee', link: 'https://etienne-bernoux.github.io/carillon/', img: '',
    tip: { fr: 'Carillon', en: 'Carillon' },
  },
  {
    id: 'aladin', zone: 'code', top: 27, left: 9,
    name: { fr: 'Aladin.farm · Farmi', en: 'Aladin.farm · Farmi' },
    ctx: { fr: 'invivo digital factory · 2018—now', en: 'invivo digital factory · 2018—now' },
    desc: { fr: 'Plateforme B2Ag pour le monde agricole. D’abord comme consultant, puis en interne : du développement initial au pilotage.', en: 'B2Ag platform for agriculture. First as a consultant, then in-house: from initial development to technical leadership.' },
    color: '#22d3ee', link: '', img: '',
    tip: { fr: 'Aladin.farm', en: 'Aladin.farm' },
  },
  {
    id: 'gouv', zone: 'code', top: 25, left: 24,
    name: { fr: 'numerique.gouv.fr', en: 'numerique.gouv.fr' },
    ctx: { fr: 'octo · dinsic · 2019', en: 'octo · dinsic · 2019' },
    desc: { fr: 'Site officiel du numérique de l’État. Jekyll, Foundation, CircleCI.', en: 'French government digital website. Jekyll, Foundation, CircleCI.' },
    color: '#22d3ee', link: '', img: '',
    tip: { fr: '.gouv.fr', en: '.gouv.fr' },
  },
  {
    id: 'spacebreakout', zone: 'code', top: 30, left: 40,
    name: { fr: 'Space Breakout', en: 'Space Breakout' },
    ctx: { fr: 'canvas · js · 2025', en: 'canvas · js · 2025' },
    desc: { fr: 'Casse-briques spatial en pur JS Canvas. Parce que même les side projects méritent des étoiles.', en: 'Space-themed breakout game in pure JS Canvas. Because even side projects deserve stars.' },
    color: '#22d3ee', link: 'https://etienne-bernoux.github.io/space-breakout/', img: 'img/space-breakout.png',
    tip: { fr: 'Space Breakout', en: 'Space Breakout' },
  },
  {
    id: 'neuralgarden', zone: 'code', top: 39, left: 14,
    name: { fr: 'Neural Garden', en: 'Neural Garden' },
    ctx: { fr: 'rust · réseaux de neurones · 2026', en: 'rust · neural networks · 2026' },
    desc: { fr: 'Écosystème simulé où des plantes pilotées par de petits réseaux de neurones apprennent à survivre. Symbiose et invasion émergent d’elles-mêmes.', en: 'Simulated ecosystem where plants driven by tiny neural networks learn to survive. Symbiosis and invasion emerge on their own.' },
    color: '#22d3ee', link: 'https://github.com/Etienne-Bernoux/neural-garden', img: '',
    tip: { fr: 'Neural Garden', en: 'Neural Garden' },
  },
  {
    id: 'oneprompt', zone: 'code', top: 38, left: 29,
    name: { fr: 'One-Prompt Minecraft', en: 'One-Prompt Minecraft' },
    ctx: { fr: 'three.js · 1 prompt · 2026', en: 'three.js · 1 prompt · 2026' },
    desc: { fr: 'Un clone Minecraft jouable, terrain voxel procédural inclus, sorti d’un seul prompt. L’expérience qui montre où en est la barre.', en: 'A playable Minecraft clone, procedural voxel terrain included, out of a single prompt. The experiment that shows where the bar sits.' },
    color: '#22d3ee', link: 'https://etienne-bernoux.github.io/one-prompt-minecraft/', img: '',
    tip: { fr: 'One-Prompt MC', en: 'One-Prompt MC' },
  },
  {
    id: 'secondcerveau', zone: 'code', top: 42, left: 43,
    name: { fr: 'Second cerveau', en: 'Second brain' },
    ctx: { fr: 'agents · compound engineering · 2026', en: 'agents · compound engineering · 2026' },
    desc: { fr: 'Mémoire, skills et sous-agents versionnés : chaque session apprend de la précédente. L’outillage que j’affine tous les jours.', en: 'Versioned memory, skills and subagents: every session learns from the last one. The tooling I sharpen daily.' },
    color: '#22d3ee', link: '', img: '',
    tip: { fr: 'Second cerveau', en: 'Second brain' },
  },

  // ── SPATIAL ──
  {
    id: 'space-veille', zone: 'spatial', top: 20, left: 72,
    name: { fr: 'Veille aérospatiale', en: 'Aerospace watch' },
    ctx: { fr: 'passion', en: 'passion' },
    desc: { fr: 'SpaceX, Ariane, exploration spatiale. Le ciel comme horizon.', en: 'SpaceX, Ariane, space exploration. The sky as a horizon.' },
    color: '#a78bfa', link: '', img: '',
    tip: { fr: 'Veille aéro', en: 'Aerospace' },
  },
  {
    id: 'drone', zone: 'spatial', top: 32, left: 82,
    name: { fr: 'Drone ECE', en: 'ECE Drone' },
    ctx: { fr: 'ece · 2012—2014', en: 'ece · 2012—2014' },
    desc: { fr: 'Conception d’un drone sur 2 ans. Chef de projet, ECE Inov-Award.', en: 'Drone built over 2 years. Project lead, ECE Inov-Award.' },
    color: '#a78bfa', link: '', img: '',
    tip: { fr: 'Drone ECE', en: 'ECE Drone' },
  },

  // ── ATELIER ──
  {
    id: 'atelier-plan', zone: 'atelier', top: 58, left: 58,
    name: { fr: 'Plan de l’atelier', en: 'Workshop floor plan' },
    ctx: { fr: 'relevé · cotes · 2026', en: 'survey · dimensions · 2026' },
    desc: { fr: 'Croquis manuscrit devenu plan coté au millimètre. Avant de scier, on mesure — deux fois.', en: 'A hand sketch turned into a plan dimensioned to the millimetre. Measure twice, cut once.' },
    color: '#34d399', link: '', img: '',
    tip: { fr: 'Plan atelier', en: 'Workshop plan' },
  },
  {
    id: 'meubles', zone: 'atelier', top: 68, left: 70,
    name: { fr: 'Plans de meubles', en: 'Furniture plans' },
    ctx: { fr: 'bois · three.js · en cours', en: 'wood · three.js · ongoing' },
    desc: { fr: 'Conception et fabrication de meubles : vues 3D interactives et plans cotés avant la première découpe.', en: 'Furniture design and building: interactive 3D views and dimensioned plans before the first cut.' },
    color: '#34d399', link: 'https://etienne-bernoux.github.io/plan-meubles/', img: '',
    tip: { fr: 'Meubles', en: 'Furniture' },
  },
  {
    id: 'bricolage', zone: 'atelier', top: 78, left: 82,
    name: { fr: 'Bricolage', en: 'DIY' },
    ctx: { fr: 'maison · réparations', en: 'home · repairs' },
    desc: { fr: 'Tout ce qui se répare, s’améliore, se construit à la main.', en: 'Anything that can be fixed, improved, or built by hand.' },
    color: '#34d399', link: '', img: '',
    tip: { fr: 'Bricolage', en: 'DIY' },
  },

  // ── FAMILLE ──
  {
    id: 'lotohistoire', zone: 'famille', top: 60, left: 12,
    name: { fr: 'Loto d’Histoire', en: 'Loto d’Histoire' },
    ctx: { fr: 'vanilla js · ddd · 2025', en: 'vanilla js · ddd · 2025' },
    desc: { fr: 'Apprendre les grandes dates de l’Histoire de France en jouant. Découvrir, associer, restituer — pour les CE1-CE2.', en: 'Learn key dates in French history through play. Discover, match, recall — for ages 7-8.' },
    color: '#eab308', link: 'https://etienne-bernoux.github.io/loto-histoire/', img: 'img/loto-histoire.png',
    tip: { fr: 'Loto d’Histoire', en: 'Loto d’Histoire' },
  },
  {
    id: 'mathquiz', zone: 'famille', top: 70, left: 18,
    name: { fr: 'MathQuiz', en: 'MathQuiz' },
    ctx: { fr: 'react · pwa · 2025', en: 'react · pwa · 2025' },
    desc: { fr: 'App pour apprendre les tables de multiplication. Faite pour ceux qui comptent le plus.', en: 'Multiplication tables app. Built for the ones who matter most.' },
    color: '#eab308', link: 'https://etienne-bernoux.github.io/math-learner/', img: 'img/math-learner.png',
    tip: { fr: 'MathQuiz', en: 'MathQuiz' },
  },
  {
    id: 'tictacaventure', zone: 'famille', top: 80, left: 28,
    name: { fr: 'Tic Tac Aventure', en: 'Tic Tac Aventure' },
    ctx: { fr: 'vanilla js · canvas · 2025', en: 'vanilla js · canvas · 2025' },
    desc: { fr: 'Apprendre à lire l’heure en s’amusant. Horloge interactive, niveaux et badges pour les petits explorateurs.', en: 'Learn to read time through play. Interactive clock, levels and badges for little explorers.' },
    color: '#eab308', link: 'https://etienne-bernoux.github.io/tic-tac-aventure/', img: 'img/tic-tac-aventure.png',
    tip: { fr: 'Tic Tac Aventure', en: 'Tic Tac Aventure' },
  },
]);
